-- Create Rivalries Table
create table if not exists rivalries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  started_at timestamp with time zone,
  
  -- Foreign Keys linking to users
  challenger_id uuid references auth.users not null,
  opponent_id uuid references auth.users not null,
  
  -- Display Names (cached from profiles to avoid complex joins)
  challenger_name text not null,
  opponent_name text not null,
  
  -- Driver Selections
  challenger_driver text,
  opponent_driver text,
  
  -- Stats
  race_duration int default 1,
  races_completed int default 0,
  
  challenger_points int default 0,
  opponent_points int default 0,
  
  -- Status
  status text default 'pending' check (status in ('pending', 'active', 'completed', 'declined'))
);

-- Row Level Security
alter table rivalries enable row level security;

-- Policies
create policy "Users can see all rivalries"
on rivalries for select
using (true);

create policy "Users can insert rivalries"
on rivalries for insert
with check (auth.uid() = challenger_id);

create policy "Users can update their own rivalries"
on rivalries for update
using (auth.uid() = challenger_id or auth.uid() = opponent_id);
